# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Queue-Worker
version:      0.01
version_from: lib/Queue/Worker.pm
installdirs:  site
requires:
    POSIX::RT::Semaphore:          
    Test::Simple:                  0.44
    Test::TempDatabase:            0.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
